spring:
  datasource:
    name: slow_song_test
    url: jdbc:mysql://localhost:3306/slow_song_test
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fuller.slowsong.bean